### ISSUE TITLE
tailwind.config.js not mentioned in blog post

### ISSUE THREAD

**Issue by jeroenherczeg** [larapeak/laravel7-tailwindcss#2]
Hi,

Thank you for the tutorial on https://www.larapeak.com/blog/setup-tailwindcss-in-laravel-7/.
I followed this and had to additionally add a tailwind.config.js file.
This was not mentioned in the blog post.
After adding this, it worked!

Thank you!

**Comment by larapeak** [comment]
Hi @jeroenherczeg,

Thanks for your message, I have added it to the tutorial!
Have a nice day!!

**Comment by jeroenherczeg** [comment]
👍
